--1
--procedure which create order with products and realizations connected to specific employee and product_types



--2
--remove product_type which was sold least times



--3
--decrease salary of employee when his total profit (function below) in month is lower than salary



--function
--returns total profit generated by employee in period of time